# Generated by Django 4.0.4 on 2022-07-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.IntegerField(max_length=20)),
                ('stock', models.IntegerField(max_length=20)),
                ('imagen', models.CharField(default='imagen', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=16)),
                ('apellido', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('ciudad', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=12)),
            ],
        ),
    ]
