# Generated by Django 4.0.4 on 2022-07-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('porcentaje', models.IntegerField(max_length=3)),
            ],
        ),
    ]
