# Generated by Django 4.0.4 on 2022-07-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='historial',
            name='codigo',
            field=models.AutoField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
