# Generated by Django 4.0.4 on 2022-07-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_historial_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='codigo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
