# Generated by Django 4.0.4 on 2022-07-08 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_historial_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_descuento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.descuento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_antiguo',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historial',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
