# Generated by Django 4.0.4 on 2022-07-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_id_descuento_id_descuento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_descuento',
        ),
        migrations.AddField(
            model_name='descuento',
            name='codigo',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado_promocion',
            field=models.BooleanField(default=False),
        ),
    ]
