# Generated by Django 4.0.4 on 2022-07-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_producto_id_descuento_descuento_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='codigo',
            field=models.IntegerField(default=0, max_length=5, null=True),
        ),
    ]
