# Generated by Django 4.0.4 on 2022-07-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_descuento_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('descuento', models.IntegerField(default=0)),
                ('monto', models.IntegerField(default=0)),
            ],
        ),
    ]
